fix predict function
wellcometrust/grants_tagger pull request #253
Opened 2023-05-24 14:14 UTC by AndreiXYZ

Fix predict function

2023-05-24 14:46 UTC, AndreiXYZ commented
To reproduce:
```bash
grants_tagger predict \
"Plant-based repellents have been used for generations in traditional practice as a personal protection measure against host-seeking mosquitoes. Knowledge on traditional repellent plants obtained through ethnobotanical studies is a valuable resource for the development of new natural products. Recently, commercial repellent products containing plant-based ingredients have gained increasing popularity among consumers, as these are commonly perceived as “safe” in comparison to long-established synthetic repellents although this is sometimes a misconception. To date insufficient studies have followed standard WHO Pesticide Evaluation Scheme guidelines for repellent testing. There is a need for further standardized studies in order to better evaluate repellent compounds and develop new products that offer high repellency as well as good consumer safety. This paper presents a summary of recent information on testing, efficacy and safety of plant-based repellents as well as promising new developments in the field." \
"Wellcome/WellcomeBertMesh" \
--threshold 0.5
```

2023-05-24 15:12 UTC, nsorros requested changes
- Uncommment tests and make them pass
- Add test for the erratic behaviour you were experiencing

2023-05-25 12:22 UTC, nsorros commented on tests/test_cli.py
> +    print(result)
remove

2023-05-25 12:23 UTC, nsorros commented on tests/test_predict.py
> -# import os
remove commented code

2023-05-25 12:23 UTC, nsorros approved these changes
Apoproving to unblock but remove print and comments

2023-05-25 13:38 UTC, merged